spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: >-
      jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME:smartfleetapp@smart-fleet-postgresql-server-dev}
    password: ${DB_PASSWORD}


flyway:
  locations: filesystem:db/migration